name: teka_teki_tiku
description: Aplikasi Permainan Teka-Teki
version: 1.3.0
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^8.1.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  teka_tekit: ^0.1.0+1
  teka_tecore: ^0.1.0+1
  cross_word: ^0.1.1+2
  naive_cross_word: ^0.1.1

dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
